### ISSUE TITLE
No movie poster found

### ISSUE THREAD

**Issue by BeatyPete** [clintonstrange/movie-hub#4]
I don't know if what is in the js file is just temporary or not but at some point we should add an if statement in the displayMovies function that check to make sure there is actually a movie poster to display, and if there isn't then displaying something like "No movie poster found" instead. If you want an example of the bug type "The Thing" into the search.

**Comment by clintonstrange** [comment]
Updated this function with an if conditional statement to display a "No Poster Found" image.
